(function(){
'use strict';
function createNoSpendModule(ctx){
  const {qs,esc,iso,getState,save,modal,commitNoSpendCandidate}=ctx; let editId='',logChallengeId='',logDate='',entryEditId='',showAllCheckins=false;
  const uid=()=>`nse-${Date.now()}-${Math.random().toString(36).slice(2,7)}`, money=value=>Number(value||0).toFixed(2);
  const t=(key,vars)=>window.NoSpendQuickCheckinI18n?.t?.(key,vars)||key;
  function summarize(log={}){const entries=Array.isArray(log.entries)?log.entries:null;if(entries){const total=entries.reduce((s,x)=>s+Math.max(0,Number(x.amount)||0),0),necessary=entries.filter(x=>x.necessity==='necessary').reduce((s,x)=>s+Math.max(0,Number(x.amount)||0),0);return {entries,total,necessary,unnecessary:total-necessary,count:entries.length,legacy:false,spent:total>0};}const total=Math.max(0,Number(log.amount)||0),necessary=log.spent&&log.necessary!==false?total:0;return {entries:null,total,necessary,unnecessary:total-necessary,count:log.spent?1:0,legacy:true,spent:log.spent===true};}
  const findChallenge=id=>getState().noSpendChallenges.find(x=>String(x.id)===String(id));
  const findLog=(item,date)=>(item?.logs||[]).find(x=>x.date===date)||null;
  const localDay=value=>iso(value instanceof Date?value:new Date(String(value||'').includes('T')?value:String(value||'')+'T12:00:00'));
  function logStatus(log){if(!log)return 'unrecorded';if(log.status==='no_spend'||log.status==='spent')return log.status;return summarize(log).spent?'spent':'no_spend';}
  function dateRange(item,today=iso(new Date())){const out=[],start=new Date(item.startDate+'T12:00:00'),end=new Date(Math.min(new Date(item.endDate+'T12:00:00').getTime(),new Date(today+'T12:00:00').getTime()));for(let d=new Date(start);d<=end;d.setDate(d.getDate()+1))out.push(localDay(d));return out;}
  function getUnrecordedNoSpendDates(item,today=iso(new Date())){return dateRange(item,today).filter(date=>!findLog(item,date));}
  function countNoSpendDays(item,{month='' }={}){return (item?.logs||[]).filter(log=>(!month||String(log.date||'').startsWith(month))&&logStatus(log)==='no_spend').length;}
  function setNoSpendStatus(id,date,status){const current=getState(),item=findChallenge(id),today=iso(new Date());if(!item||!['no_spend','spent'].includes(status)||date<item.startDate||date>item.endDate||date>today)return {ok:false,message:'日期不可记录'};const candidate=JSON.parse(JSON.stringify(current)),next=(candidate.noSpendChallenges||[]).find(x=>String(x.id)===String(id));next.logs=Array.isArray(next.logs)?next.logs:[];let log=next.logs.find(x=>x.date===date);if(!log){log={date,entries:[],createdAt:Date.now()};next.logs.push(log);}log.status=status;log.spent=status==='spent';log.updatedAt=Date.now();next.updatedAt=Date.now();const result=commitNoSpendCandidate?.(candidate,{challengeId:id,date,expectedStatus:status});if(!result?.ok){alert(t('saveFailed'));return result;}render();window.renderTodayHub?.();return result;}
  function setNoSpendDays(days){qs('#nsDays').value=days;}
  function openNoSpendEditor(id=''){editId=id;const item=id?findChallenge(id):null;qs('#noSpendModalTitle').textContent=item?'编辑 No Spend Challenge':'新建 No Spend Challenge';qs('#nsTitle').value=item?.title||'';qs('#nsStart').value=item?.startDate||iso(new Date());qs('#nsDays').value=item?.days||30;qs('#nsRules').value=item?.rules||'';qs('#nsAllowed').value=item?.allowed||'';qs('#nsWeeklyReview').value=item?.weeklyReview||'';qs('#nsFinalReview').value=item?.finalReview||'';modal.open('noSpendModal');}
  function closeNoSpendEditor(){modal.close('noSpendModal');}
  function saveNoSpend(){const state=getState(),title=qs('#nsTitle').value.trim()||'No Spend Challenge',startDate=qs('#nsStart').value||iso(new Date()),days=Math.max(1,Number(qs('#nsDays').value)||30),d={title,startDate,days,endDate:iso(new Date(new Date(startDate+'T12:00:00').getTime()+(days-1)*86400000)),rules:qs('#nsRules').value.trim(),allowed:qs('#nsAllowed').value.trim(),weeklyReview:qs('#nsWeeklyReview').value.trim(),finalReview:qs('#nsFinalReview').value.trim(),updatedAt:Date.now()};if(editId)Object.assign(findChallenge(editId),d);else state.noSpendChallenges.push({id:uid(),...d,logs:[],status:'active',createdAt:Date.now()});const result=save();if(!result?.ok)return result;closeNoSpendEditor();render();return result;}
  function deleteNoSpend(id){if(confirm('确定删除这个 No Spend Challenge 吗？')){getState().noSpendChallenges=getState().noSpendChallenges.filter(x=>x.id!==id);save();render();}}
  const currentLog=()=>findLog(findChallenge(logChallengeId),logDate);
  function renderLog(){const log=currentLog(),s=summarize(log||{}),summary=qs('#nsLogSummary'),list=qs('#nsLogEntries');if(!summary||!list)return;summary.innerHTML=`<div class="metric-row compact-metrics"><div class="metric"><b>$${money(s.total)}</b><span>今日消费总额</span></div><div class="metric"><b>${s.count}</b><span>今日共 ${s.count} 笔</span></div><div class="metric"><b>$${money(s.necessary)}</b><span>必要消费</span></div><div class="metric"><b>$${money(s.unnecessary)}</b><span>非必要消费</span></div></div><p class="section-note">今日 No Spend 状态：<b>${s.spent?'已消费':'No Spend'}</b>${s.legacy&&s.count?' · 历史汇总记录':''}</p>`;if(s.legacy&&s.count){list.innerHTML=`<div class="entry"><b>历史消费汇总</b><p>$${money(s.total)} · ${log.necessary===false?'非必要':'必要'}${log.reason?` · ${esc(log.reason)}`:''}</p><small>此历史记录保留原统计，未伪造消费明细。</small></div>`;return;}list.innerHTML=s.entries?.length?s.entries.map(x=>`<article class="entry no-spend-entry" data-no-spend-entry-id="${esc(x.id)}"><button type="button" class="no-spend-entry-main" onclick="editNoSpendEntry('${esc(x.id)}')"><b>${esc(x.merchant||x.category||'消费')}</b><span>$${money(x.amount)} · ${x.necessity==='necessary'?'必要':'非必要'}${x.category&&x.merchant?` · ${esc(x.category)}`:''}${x.note?`<small>${esc(x.note)}</small>`:''}</span></button><button type="button" class="danger icon-action" onclick="deleteNoSpendEntry('${esc(x.id)}')">删除</button></article>`).join(''):'<div class="entry"><span class="small">今天还没有消费明细。</span></div>';}
  function openNoSpendLog(id,date=''){if(!findChallenge(id))return;logChallengeId=id;logDate=date||iso(new Date());qs('#nsLogDate').value=logDate;renderLog();modal.open('noSpendLogModal');}
  function setNoSpendLogDate(date){if(!/^\d{4}-\d{2}-\d{2}$/.test(String(date||'')))return;logDate=String(date);entryEditId='';renderLog();}
  function closeNoSpendLog(){modal.close('noSpendLogModal');}
  function openNoSpendEntry(id=''){if(summarize(currentLog()||{}).legacy&&currentLog()?.spent){alert('历史汇总记录会保留原始统计，不能添加虚构明细。');return;}const row=(currentLog()?.entries||[]).find(x=>x.id===id);entryEditId=id;qs('#nsEntryTitle').textContent=row?'编辑一笔消费':'增加一笔消费';qs('#nsEntryAmount').value=row?.amount??'';qs('#nsEntryNecessity').value=row?.necessity||'necessary';qs('#nsEntryCategory').value=row?.category||'';qs('#nsEntryMerchant').value=row?.merchant||'';qs('#nsEntryNote').value=row?.note||'';modal.push('noSpendLogModal','noSpendEntryModal',{challengeId:logChallengeId,date:logDate});}
  function editNoSpendEntry(id){openNoSpendEntry(id);}
  function closeNoSpendEntry(){entryEditId='';modal.pop('noSpendEntryModal');renderLog();}
  function saveNoSpendEntry(){const item=findChallenge(logChallengeId);if(!item)return;item.logs=Array.isArray(item.logs)?item.logs:[];let log=findLog(item,logDate);if(!log){log={date:logDate,entries:[],createdAt:Date.now()};item.logs.push(log);}if(!Array.isArray(log.entries))log.entries=[];const amount=Math.max(0,Number(qs('#nsEntryAmount').value)||0);if(amount<=0){alert('请输入大于 0 的金额。');return;}const old=log.entries.find(x=>x.id===entryEditId),data={id:entryEditId||uid(),amount,necessity:qs('#nsEntryNecessity').value==='unnecessary'?'unnecessary':'necessary',category:qs('#nsEntryCategory').value.trim(),merchant:qs('#nsEntryMerchant').value.trim(),note:qs('#nsEntryNote').value.trim(),createdAt:old?.createdAt||Date.now(),updatedAt:Date.now()};if(old)Object.assign(old,data);else log.entries.push(data);log.spent=summarize(log).spent;log.updatedAt=Date.now();item.updatedAt=Date.now();const result=save();if(!result?.ok)return result;entryEditId='';modal.pop('noSpendEntryModal');renderLog();render();return result;}
  function deleteNoSpendEntry(id){const item=findChallenge(logChallengeId),log=currentLog();if(!item||!log||!Array.isArray(log.entries)||!confirm('删除这笔消费吗？'))return;log.entries=log.entries.filter(x=>x.id!==id);log.spent=summarize(log).spent;log.updatedAt=Date.now();item.updatedAt=Date.now();save();renderLog();render();}
  function totals(item){return (item.logs||[]).reduce((r,log)=>{const s=summarize(log);r.total+=s.total;r.unnecessary+=s.unnecessary;r.noSpend+=logStatus(log)==='no_spend'?1:0;return r;},{total:0,unnecessary:0,noSpend:0});}
  function toggleNoSpendCheckinView(){showAllCheckins=!showAllCheckins;render();}
  function dailyRows(item){const all=dateRange(item),dates=(showAllCheckins?all:all.slice(-7)).reverse(),view=all.length>7?`<button class="ghost no-spend-view-all" onclick="toggleNoSpendCheckinView()">${esc(t('viewAll'))}</button>`:'';return `<div class="no-spend-checkins"><div class="section-head"><b>${esc(t('dailyCheckin'))}</b>${view}</div>${dates.map(date=>{const status=logStatus(findLog(item,date)),future=date>iso(new Date()),label=t(status==='no_spend'?'noSpend':status==='spent'?'spent':'unrecorded');return `<div class="no-spend-checkin-row"><span>${date} · ${esc(label)}</span>${future?'':status==='unrecorded'?`<button aria-label="${esc(date+' '+t('noSpend'))}" onclick="setNoSpendStatus('${item.id}','${date}','no_spend')">${esc(t('noSpend'))}</button><button aria-label="${esc(date+' '+t('spent'))}" onclick="setNoSpendStatus('${item.id}','${date}','spent')">${esc(t('spent'))}</button>`:`<button aria-label="${esc(date+' '+t('edit'))}" onclick="openNoSpendLog('${item.id}','${date}')">${esc(t('edit'))}</button>`}</div>`;}).join('')}</div>`;}
  function render(){const el=qs('#noSpendList');if(!el)return;const list=getState().noSpendChallenges.slice().sort((a,b)=>(b.updatedAt||0)-(a.updatedAt||0));el.innerHTML=list.length?list.map(item=>{const summary=totals(item),pct=Math.min(100,Math.round(summary.noSpend/Math.max(1,item.days)*100)),backlog=getUnrecordedNoSpendDates(item).filter(date=>date<iso(new Date())).length;return `<div class="tool-card" data-challenge-id="${esc(item.id)}"><div class="tool-card-head"><div><h3>${esc(item.title)}</h3><div class="meta">${esc(item.startDate)} → ${esc(item.endDate)} · ${item.days} 天</div></div><span class="status-pill">${summary.noSpend}/${item.days} ${esc(t('noSpend'))}</span></div><div class="progress"><i style="width:${pct}%"></i></div>${backlog?`<p class="section-note">${esc(backlog===1?t('awaitingOne'):t('awaitingMany',{n:backlog}))}</p>`:''}${dailyRows(item)}<div class="tool-actions"><button onclick="openNoSpendLog('${item.id}')">${esc(t('today'))}</button><button onclick="openNoSpendEditor('${item.id}')">${esc(t('edit'))}</button><button class="danger" onclick="deleteNoSpend('${item.id}')">${esc(t('delete'))}</button></div></div>`;}).join(''):'<div class="entry"><span class="small">还没有 No Spend Challenge。</span></div>';}
  return {render,openNoSpendEditor,closeNoSpendEditor,setNoSpendDays,saveNoSpend,openNoSpendLog,setNoSpendLogDate,closeNoSpendLog,openNoSpendEntry,editNoSpendEntry,closeNoSpendEntry,saveNoSpendEntry,deleteNoSpendEntry,deleteNoSpend,setNoSpendStatus,toggleNoSpendCheckinView,countNoSpendDays,__test:{summarize,logStatus,getUnrecordedNoSpendDates,dateRange,countNoSpendDays}};
}
window.JournalModules=window.JournalModules||{};window.JournalModules.createNoSpendModule=createNoSpendModule;
})();
