(function(){
'use strict';
function createCollectionsModule(ctx){
 const {qs,esc,getState,save,modal}=ctx;let editListId='',activeListId='',editItemId='';
 const uid=p=>`${p}-${Date.now()}-${Math.random().toString(36).slice(2,7)}`;
 function openWishlistEditor(id=''){editListId=id;const x=id?getState().wishlists.find(v=>v.id===id):null;qs('#wishlistModalTitle').textContent=x?'编辑 Wish List':'新建 Wish List';qs('#wishlistName').value=x?.name||'';qs('#wishlistNotes').value=x?.notes||'';modal.open('wishlistModal')}
 function closeWishlistEditor(){modal.close('wishlistModal')}
 function saveWishlist(){const s=getState(),d={name:qs('#wishlistName').value.trim()||'Wish List',notes:qs('#wishlistNotes').value.trim(),updatedAt:Date.now()};if(editListId){const x=s.wishlists.find(v=>v.id===editListId);if(x)Object.assign(x,d)}else s.wishlists.push({id:uid('wishlist'),items:[],createdAt:Date.now(),...d});save();closeWishlistEditor();renderWishlists()}
 function deleteWishlist(id){const s=getState();if(!confirm('确定删除这个 Wish List 及其所有 items 吗？'))return;s.wishlists=s.wishlists.filter(x=>x.id!==id);save();renderWishlists()}
 function openWishlistItems(id){activeListId=id;renderWishlistItems();modal.open('wishlistItemsModal')}
 function closeWishlistItems(){modal.close('wishlistItemsModal')}
 function openWishlistItemEditor(id=''){editItemId=id;const list=getState().wishlists.find(x=>x.id===activeListId);if(!list)return;const x=id?(list.items||[]).find(v=>v.id===id):null;qs('#wiName').value=x?.name||'';qs('#wiPrice').value=x?.price??'';qs('#wiStore').value=x?.store||'';qs('#wiStatus').value=x?.status||'watching';qs('#wiNotes').value=x?.notes||'';if(modal.isOpen('wishlistItemsModal'))modal.push('wishlistItemsModal','wishlistItemModal',{flow:'wishlist-items-item-editor',listId:activeListId});else modal.open('wishlistItemModal')}
 function closeWishlistItemEditor(){modal.pop('wishlistItemModal')}
 function saveWishlistItem(){const list=getState().wishlists.find(x=>x.id===activeListId);if(!list)return;list.items=Array.isArray(list.items)?list.items:[];const d={name:qs('#wiName').value.trim()||'Wish Item',price:Math.max(0,Number(qs('#wiPrice').value)||0),store:qs('#wiStore').value.trim(),status:qs('#wiStatus').value,notes:qs('#wiNotes').value.trim(),updatedAt:Date.now()};if(editItemId){const x=list.items.find(v=>v.id===editItemId);if(x)Object.assign(x,d)}else list.items.push({id:uid('wishitem'),createdAt:Date.now(),...d});list.updatedAt=Date.now();save();renderWishlistItems();renderWishlists();modal.pop('wishlistItemModal')}
 function deleteWishlistItem(id){const list=getState().wishlists.find(x=>x.id===activeListId);if(!list||!confirm('确定删除这个 Wish Item 吗？'))return;list.items=(list.items||[]).filter(x=>x.id!==id);list.updatedAt=Date.now();save();renderWishlistItems();renderWishlists()}
 function renderWishlistItems(){const list=getState().wishlists.find(x=>x.id===activeListId);if(!list)return;qs('#wishlistItemsTitle').textContent=list.name;const items=(list.items||[]).slice().sort((a,b)=>(b.updatedAt||0)-(a.updatedAt||0));qs('#wishlistItems').innerHTML=items.length?items.map(x=>`<div class="collection-item"><div class="collection-item-head"><div><h4>${esc(x.name)}</h4><div class="meta">${esc(x.store||'')} ${x.price?'· '+Number(x.price).toFixed(2):''}</div></div><span class="status-pill">${esc(x.status)}</span></div>${x.notes?`<div class="meta" style="margin-top:7px">${esc(x.notes)}</div>`:''}<div class="tool-actions"><button onclick="openWishlistItemEditor('${x.id}')">编辑</button><button class="danger" onclick="deleteWishlistItem('${x.id}')">删除</button></div></div>`).join(''):'<div class="entry"><span class="small">这个清单还没有 item。</span></div>'}
 function renderWishlists(){const el=qs('#wishlistList');if(!el)return;const ls=getState().wishlists.slice().sort((a,b)=>(b.updatedAt||0)-(a.updatedAt||0));el.innerHTML=ls.length?ls.map(x=>{const items=x.items||[],p=items.filter(i=>i.status==='purchased').length;return `<div class="tool-card"><div class="tool-card-head"><div><h3>${esc(x.name)}</h3><div class="meta">${items.length} items · ${p} 已购买</div></div></div>${x.notes?`<div class="meta" style="margin-top:7px">${esc(x.notes)}</div>`:''}<div class="tool-actions"><button onclick="openWishlistItems('${x.id}')">打开</button><button onclick="openWishlistEditor('${x.id}')">编辑</button><button class="danger" onclick="deleteWishlist('${x.id}')">删除</button></div></div>`}).join(''):'<div class="entry"><span class="small">还没有 Wish List。可以按用途建立多个独立清单。</span></div>'}
 return{renderWishlists,openWishlistEditor,closeWishlistEditor,saveWishlist,deleteWishlist,openWishlistItems,closeWishlistItems,openWishlistItemEditor,closeWishlistItemEditor,saveWishlistItem,deleteWishlistItem}
}
window.JournalModules=window.JournalModules||{};window.JournalModules.createCollectionsModule=createCollectionsModule;
})();
