(function(){
  'use strict';
  const PRESET_CATEGORIES=['Food / 食品','Pantry / 储藏食品','Drinks / 饮品','Household / 家居用品','Cleaning / 清洁用品','Toiletries / 洗护','Baby / 宝宝用品','Medicine / 药品','Pet / 宠物用品','Office / 办公用品','Clothing / 衣物','Other / 其他'];
  const PRESET_LOCATIONS=['Kitchen','Pantry','Fridge','Freezer','Bathroom','Bedroom','Basement','Garage','Storage Room','Closet','Baby Room','Other'];
  const UNITS=['pcs','pack','box','bag','bottle','can','roll','jar','kg','g','L','mL','custom'];
  function createInventoryUseOneLogic(){
    const copy=value=>JSON.parse(JSON.stringify(value));
    function stageQuantity(source,itemId,nextQuantity,kind,message,now){
      const candidate=copy(source),items=candidate.inventory?.items;
      if(!Array.isArray(items))return {ok:false,reason:'missing_inventory'};
      const item=items.find(entry=>String(entry?.id)===String(itemId));
      if(!item)return {ok:false,reason:'missing_item'};
      const previousQuantity=Math.max(0,Number(item.quantity)||0),normalizedNext=Math.max(0,Number(nextQuantity)||0);
      item.quantity=normalizedNext;item.updatedAt=now;
      item.history=Array.isArray(item.history)?item.history:[];
      item.history.push({id:`inventory-history-${now}-${kind}`,date:new Date(now).toISOString(),kind,message,oldQuantity:previousQuantity,newQuantity:normalizedNext,quantityDelta:normalizedNext-previousQuantity});
      return {ok:true,candidate,itemId:String(item.id),previousQuantity,nextQuantity:normalizedNext};
    }
    function stageUseOne(source,itemId,now=Date.now()){
      const item=source?.inventory?.items?.find(entry=>String(entry?.id)===String(itemId));
      const quantity=Math.max(0,Number(item?.quantity)||0);
      if(!item)return {ok:false,reason:'missing_item'};
      if(quantity<=0)return {ok:false,reason:'empty'};
      return stageQuantity(source,item.id,Math.max(0,quantity-1),'quick_use_one','库存快速减少 1',now);
    }
    function stageUndo(source,undo,now=Date.now()){
      if(!undo||!undo.itemId)return {ok:false,reason:'missing_undo'};
      const item=source?.inventory?.items?.find(entry=>String(entry?.id)===String(undo.itemId));
      if(!item)return {ok:false,reason:'missing_item'};
      if(Number(item.quantity)!==Number(undo.nextQuantity))return {ok:false,reason:'stale_undo'};
      return stageQuantity(source,item.id,undo.previousQuantity,'quick_use_one_undo','撤销库存快速减少 1',now);
    }
    return {stageUseOne,stageUndo};
  }
  function createInventorySortLogic(){
    const modes=['added','updated','created','az','za','quantityAsc','quantityDesc','expiry'];
    function validSort(value){return modes.includes(value);}
    function sortItems(sort,canonicalItems=[]){const fallbackIndex=new Map((canonicalItems||[]).map((item,index)=>[String(item?.id),index]));const creationKey=item=>{const created=Number(item?.createdAt);return Number.isFinite(created)&&created>0?[0,created]:[1,fallbackIndex.get(String(item?.id))??Number.MAX_SAFE_INTEGER];};return (a,b)=>{if(sort==='added'){const ak=creationKey(a),bk=creationKey(b);return ak[0]-bk[0]||ak[1]-bk[1];}if(sort==='az')return String(a.name||'').localeCompare(String(b.name||''));if(sort==='za')return String(b.name||'').localeCompare(String(a.name||''));if(sort==='quantityAsc')return Number(a.quantity)-Number(b.quantity);if(sort==='quantityDesc')return Number(b.quantity)-Number(a.quantity);if(sort==='expiry')return (a.expiryDate||'9999-12-31').localeCompare(b.expiryDate||'9999-12-31');if(sort==='created')return (b.createdAt||0)-(a.createdAt||0);return (b.updatedAt||0)-(a.updatedAt||0);};}
    return {validSort,sortItems};
  }
  function createInventoryModule(ctx){
    const {qs,esc,iso,getState,save,commitInventoryCandidate,modal,media,inventoryI18n,inventoryDiagnostics}=ctx;
    const diag=inventoryDiagnostics||{record:()=>{},readPersistedItem:()=>null,itemSnapshot:x=>x};
    const useOneLogic=createInventoryUseOneLogic(),sortLogic=createInventorySortLogic(),i18n=inventoryI18n||{t:key=>key};
    const SORT_OPTIONS=[['added','addedOrder'],['updated','recentlyUpdated'],['created','recentlyAdded'],['az','nameAZ'],['za','nameZA'],['quantityAsc','quantityAsc'],['quantityDesc','quantityDesc'],['expiry','expiry']];
    let editId='', detailId='', editorReturnToDetail=false, pendingImageFile=null, previewUrl='', activeFilter='all',useOneUndo=null,useOneTimer=null,useOneNotice=null,sortInitialized=false;
    const today=()=>iso(new Date());
    function inv(){const s=getState();if(!s.inventory||typeof s.inventory!=='object')s.inventory={items:[],categories:[],locations:[]};s.inventory.items=Array.isArray(s.inventory.items)?s.inventory.items:[];s.inventory.categories=Array.isArray(s.inventory.categories)?s.inventory.categories:[];s.inventory.locations=Array.isArray(s.inventory.locations)?s.inventory.locations:[];s.inventory.items.forEach(item=>{item.sourceOrders=Array.isArray(item.sourceOrders)?item.sourceOrders:(item.sourceOrderId?[{orderId:item.sourceOrderId,orderItemId:'',quantity:0,importedAt:item.lastRestockedAt||''}]:[]);item.history=Array.isArray(item.history)?item.history:[]});return s.inventory;}
    function normalized(v){return String(v||'').toLowerCase().replace(/[^a-z0-9\u4e00-\u9fff]+/g,' ').trim();}
    function tokens(v){return new Set(normalized(v).split(' ').filter(Boolean));}
    function itemStatus(item){const q=Number(item.quantity)||0,min=Number(item.minQuantity)||0,expiry=item.expiryDate||'',now=today();if(expiry&&expiry<now)return 'expired';if(expiry){const d=new Date(now+'T12:00:00');d.setDate(d.getDate()+7);if(expiry<=iso(d))return 'expiring';}if(item.lowStockEnabled&&q<=min)return 'low';return '';}
    function allCategories(){return [...new Set([...PRESET_CATEGORIES,...inv().categories])].sort((a,b)=>a.localeCompare(b));}
    function allLocations(){return [...new Set([...PRESET_LOCATIONS,...inv().locations])].sort((a,b)=>a.localeCompare(b));}
    function fmt(item){const q=Number(item.quantity)||0;return `${q} ${item.unit||'pcs'}`.trim();}
    function validSort(value){return sortLogic.validSort(value);}
    function savedSort(){const mode=getState().settings?.inventorySortMode;return validSort(mode)?mode:'added';}
    function currentSort(){const el=qs('#inventorySort'),saved=savedSort();if(el&&(!sortInitialized||!validSort(el.value))){el.innerHTML=SORT_OPTIONS.map(([mode,label])=>`<option value="${mode}">${esc(i18n.t(label))}</option>`).join('');el.value=saved;sortInitialized=true;}return validSort(el?.value)?el.value:saved;}
    function setSort(mode){if(!validSort(mode))return {ok:false,reason:'invalid_sort'};const settings=getState().settings||(getState().settings={theme:'sage'}),previous=savedSort();if(previous===mode){sortInitialized=false;render();return {ok:true,unchanged:true};}settings.inventorySortMode=mode;const result=save();if(!result?.ok){sortInitialized=false;render();return result;}sortInitialized=false;render();return result;}
    function clearUseOneTimer(){if(useOneTimer){clearTimeout(useOneTimer);useOneTimer=null;}}
    function setUseOneNotice(message,error=false){useOneNotice={message,error};}
    function scheduleUndoExpiry(){clearUseOneTimer();useOneTimer=setTimeout(()=>{useOneUndo=null;useOneNotice=null;render();},8000);}
    function renderUseOneSnackbar(){const el=qs('#inventoryUseOneSnackbar');if(!el)return;el.hidden=!useOneNotice;el.classList.toggle('error',!!useOneNotice?.error);el.innerHTML=useOneNotice?`<span>${esc(useOneNotice.message)}</span>${useOneUndo&&!useOneNotice.error?`<button type="button" onclick="undoInventoryUseOne(event)">${esc(i18n.t('undo'))}</button>`:''}`:'';}
    function refreshAfterUseOne(){render();hydrateImages();}
    function useOne(id,event){event?.stopPropagation?.();const staged=useOneLogic.stageUseOne(getState(),id);if(!staged.ok){setUseOneNotice(i18n.t('cannotUse'),true);refreshAfterUseOne();return staged;}const result=commitInventoryCandidate?.(staged.candidate,{itemId:staged.itemId,expectedQuantity:staged.nextQuantity});if(!result?.ok){setUseOneNotice(i18n.t('saveFailed'),true);refreshAfterUseOne();return result;}useOneUndo={itemId:staged.itemId,previousQuantity:staged.previousQuantity,nextQuantity:staged.nextQuantity,expiresAt:Date.now()+8000};setUseOneNotice(i18n.t('reduced'));scheduleUndoExpiry();refreshAfterUseOne();return result;}
    function undoUseOne(event){event?.stopPropagation?.();if(!useOneUndo||Date.now()>useOneUndo.expiresAt){useOneUndo=null;setUseOneNotice(i18n.t('undoUnavailable'),true);refreshAfterUseOne();return {ok:false,reason:'expired_undo'};}const staged=useOneLogic.stageUndo(getState(),useOneUndo);if(!staged.ok){useOneUndo=null;setUseOneNotice(i18n.t('undoUnavailable'),true);refreshAfterUseOne();return staged;}const result=commitInventoryCandidate?.(staged.candidate,{itemId:staged.itemId,expectedQuantity:staged.nextQuantity});if(!result?.ok){setUseOneNotice(i18n.t('undoFailed'),true);refreshAfterUseOne();return result;}clearUseOneTimer();useOneUndo=null;useOneNotice=null;refreshAfterUseOne();return result;}
    function setPreview(record){const img=qs('#inventoryImagePreview');if(previewUrl){URL.revokeObjectURL(previewUrl);previewUrl='';}if(record?.blob)previewUrl=URL.createObjectURL(record.blob);img.src=previewUrl||'';img.hidden=!previewUrl;qs('#inventoryImageEmpty').hidden=!!previewUrl;}
    async function showImage(id){if(!id){setPreview(null);return;}try{setPreview(await media.get(id));}catch(_){setPreview(null);}}
    function fillSelect(id,values,current,customLabel){const el=qs('#'+id);el.innerHTML=values.map(v=>`<option value="${esc(v)}">${esc(v)}</option>`).join('')+`<option value="__custom__">${customLabel}</option>`;const found=values.includes(current);el.value=found?current:'__custom__';qs('#'+id+'Custom').value=found?'':(current||'');qs('#'+id+'Custom').hidden=found;}
    function toggleCustom(id){qs('#'+id+'Custom').hidden=qs('#'+id).value!=='__custom__';}
    function editorValues(){return {name:qs('#invName').value,category:selectValue('invCategory'),quantity:qs('#invQuantity').value,unit:qs('#invUnit').value==='custom'?qs('#invUnitCustom').value:qs('#invUnit').value,location:selectValue('invLocation'),purchaseDate:qs('#invPurchaseDate').value,expiryDate:qs('#invExpiryDate').value,minQuantity:qs('#invMinQuantity').value,notes:qs('#invNotes').value,tags:qs('#invTags').value};}
    function bindFieldTrace(item){for(const id of ['invName','invCategory','invCategoryCustom','invQuantity','invUnit','invUnitCustom','invLocation','invLocationCustom','invPurchaseDate','invExpiryDate','invMinQuantity','invLowStockEnabled','invTags','invNotes']){const field=qs('#'+id);if(!field)continue;field.dataset.inventoryDiagnosticOld=field.type==='checkbox'?String(field.checked):field.value;if(field.dataset.inventoryDiagnosticBound)continue;field.dataset.inventoryDiagnosticBound='true';field.addEventListener('change',()=>{const oldValue=field.dataset.inventoryDiagnosticOld,newValue=field.type==='checkbox'?String(field.checked):field.value;if(oldValue!==newValue){diag.record('field change detected',{itemId:editId,itemName:inv().items.find(x=>String(x.id)===String(editId))?.name||'',field:id,oldValue,newValue});field.dataset.inventoryDiagnosticOld=newValue;}});}}
    function openItemEditor(id='',options={}){editId=id;editorReturnToDetail=!!options.returnToDetail;pendingImageFile=null;qs('#inventoryModal').dataset.itemId=String(id||'');diag.record('inventory_editor_opened',{itemId:id,itemName:'',editorItemId:editId,returnToDetail:editorReturnToDetail});const item=id?inv().items.find(x=>String(x.id)===String(id)):null;diag.record('current record lookup start',{itemId:id,editorItemId:editId});diag.record('current record lookup end',{itemId:id,result:item?'found':'missing',record:diag.itemSnapshot(item)});qs('#inventoryModalTitle').textContent=item?'编辑库存物品':'新增库存物品';qs('#invName').value=item?.name||'';fillSelect('invCategory',allCategories(),item?.category||'', '自定义分类');fillSelect('invLocation',allLocations(),item?.location||'', '自定义位置');qs('#invQuantity').value=item?.quantity??'';qs('#invUnit').value=UNITS.includes(item?.unit)?item.unit||'pcs':'custom';qs('#invUnitCustom').value=UNITS.includes(item?.unit)?'':item?.unit||'';qs('#invUnitCustom').hidden=qs('#invUnit').value!=='custom';qs('#invPurchaseDate').value=item?.purchaseDate||'';qs('#invExpiryDate').value=item?.expiryDate||'';qs('#invMinQuantity').value=item?.minQuantity??'';qs('#invLowStockEnabled').checked=item?.lowStockEnabled!==false;qs('#invTags').value=(item?.tags||[]).join(', ');qs('#invNotes').value=item?.notes||'';qs('#inventoryImage').value='';qs('#inventorySimilar').hidden=true;bindFieldTrace(item);diag.record('form hydrated',{itemId:editId,itemName:item?.name||'',form:editorValues()});showImage(item?.imageRef);if(!modal.isOpen('inventoryModal'))modal.open('inventoryModal');}
    function closeItemEditor(){const returnToDetail=editorReturnToDetail;diag.record('modal close',{itemId:editId,itemName:inv().items.find(x=>String(x.id)===String(editId))?.name||'',modal:'inventoryModal',returnToDetail});editorReturnToDetail=false;pendingImageFile=null;setPreview(null);if(returnToDetail){modal.pop('inventoryModal');renderItemDetail(detailId);return;}modal.close('inventoryModal');}
    function selectValue(id){const v=qs('#'+id).value;return v==='__custom__'?qs('#'+id+'Custom').value.trim():v;}
    function updateSimilar(){const name=qs('#invName').value.trim(),category=selectValue('invCategory'),out=qs('#inventorySimilar');if(!name){out.hidden=true;return;}const a=tokens(name), matches=inv().items.filter(i=>i.status!=='archived'&&i.id!==editId).filter(i=>{const b=tokens(i.name),overlap=[...a].filter(x=>x.length>2&&b.has(x)).length;return normalized(i.name)===normalized(name)||(overlap>0&&(!category||i.category===category));}).slice(0,3);out.hidden=!matches.length;out.innerHTML=matches.length?`可能已有类似物品：${matches.map(i=>`<button type="button" onclick="openInventoryItem('${i.id}')">${esc(i.name)}</button>`).join('、')}`:'';}
    async function imageChanged(){const file=qs('#inventoryImage').files?.[0];if(!file)return;pendingImageFile=file;setPreview({blob:file});}
    function usedByOther(imageRef,id){return inv().items.some(i=>i.id!==id&&i.imageRef===imageRef);}
    async function saveItem(){
      diag.record('save clicked',{itemId:editId,detailItemId:detailId,draftSnapshot:editorValues()});
      const name=qs('#invName').value.trim();
      diag.record('validation start',{itemId:editId});
      if(!name){diag.record('validation end',{itemId:editId,result:'failed',error:'missing name'});alert('请填写物品名称');return;}
      diag.record('validation end',{itemId:editId,result:'passed'});
      diag.record('current record lookup start',{itemId:editId,detailItemId:detailId});
      const item=editId?inv().items.find(x=>String(x.id)===String(editId)):null,oldImageRef=item?.imageRef||'',provenanceBefore={sourceOrders:JSON.parse(JSON.stringify(item?.sourceOrders||[])),history:JSON.parse(JSON.stringify(item?.history||[]))};
      diag.record('current record lookup end',{itemId:editId,result:item?'found':'new',record:diag.itemSnapshot(item)});
      const category=selectValue('invCategory')||'Other / 其他',location=selectValue('invLocation')||'Other',unit=qs('#invUnit').value==='custom'?qs('#invUnitCustom').value.trim()||'pcs':qs('#invUnit').value;
      let newImageRef=oldImageRef;
      try{if(pendingImageFile){const saved=await media.putBlob(pendingImageFile,{ownerType:'inventory',ownerId:editId||'pending'});newImageRef=saved.id;}}catch(error){diag.record('completion/error',{itemId:editId,error:String(error?.message||error),phase:'media write'});alert('图片保存失败，请重试。');return;}
      const update={name,category,quantity:Math.max(0,Number(qs('#invQuantity').value)||0),unit,location,imageRef:newImageRef,purchaseDate:qs('#invPurchaseDate').value,expiryDate:qs('#invExpiryDate').value,minQuantity:Math.max(0,Number(qs('#invMinQuantity').value)||0),lowStockEnabled:qs('#invLowStockEnabled').checked,notes:qs('#invNotes').value.trim(),tags:qs('#invTags').value.split(',').map(x=>x.trim()).filter(Boolean),matchMeta:item?.matchMeta||{aliases:[],identifiers:{sku:[],productCode:[],upc:[]}},status:item?.status||'active',sourceOrderId:item?.sourceOrderId||'',lastRestockedAt:item?.lastRestockedAt||'',updatedAt:Date.now()};
      diag.record('requestedUpdate',{itemId:editId,editorItemId:editId,detailItemId:detailId,requestedUpdate:update,oldRecord:diag.itemSnapshot(item)});
      diag.record('merge start',{itemId:editId,mergeOrder:'old record + editable update'});
      if(item){const before=Number(item.quantity)||0,next=Number(update.quantity)||0;Object.assign(item,update);if(before!==next){item.history=Array.isArray(item.history)?item.history:[];item.history.push({id:`inventory-history-${Date.now()}`,date:new Date().toISOString(),kind:'manual_adjustment',message:'库存手动调整',oldQuantity:before,newQuantity:next,quantityDelta:next-before});}}else{const created={id:`inventory-${Date.now()}-${Math.random().toString(36).slice(2,7)}`,createdAt:Date.now(),sourceOrders:[],history:[],...update};inv().items.push(created);editId=created.id;}
      const updated=inv().items.find(x=>String(x.id)===String(editId));
      diag.record('merge end',{itemId:editId,mergedRecord:diag.itemSnapshot(updated)});
      const sourcePreserved=JSON.stringify(provenanceBefore.sourceOrders)===JSON.stringify(updated?.sourceOrders||[]),historyPreserved=provenanceBefore.history.every(old=>JSON.stringify(updated?.history||[]).includes(JSON.stringify(old)));
      diag.record('provenance preservation check',{itemId:editId,result:sourcePreserved&&historyPreserved,sourcePreserved,historyPreserved,sourceOrders:updated?.sourceOrders||[],history:updated?.history||[]});
      diag.record('media preservation check',{itemId:editId,oldImageRef,newImageRef,result:updated?.imageRef===newImageRef});
      if(pendingImageFile)try{await media.putBlob(pendingImageFile,{id:newImageRef,ownerType:'inventory',ownerId:editId});}catch(error){diag.record('completion/error',{itemId:editId,error:String(error?.message||error),phase:'media finalize'});}
      if(category&&!PRESET_CATEGORIES.includes(category)&&!inv().categories.includes(category))inv().categories.push(category);if(location&&!PRESET_LOCATIONS.includes(location)&&!inv().locations.includes(location))inv().locations.push(location);
      diag.record('persistence write start',{itemId:editId,persistenceKey:'journal-planner-v091'});const persisted=save();diag.record('persistence write end',{itemId:editId,result:persisted?.ok?'success':'failed'});
      if(!persisted?.ok){diag.record('completion/error',{itemId:editId,phase:'persistence',error:persisted?.message||'保存失败；编辑窗口保持打开。'});return persisted;}
      const readBack=diag.readPersistedItem(editId),fields=['name','quantity','location','notes','category','unit','minQuantity','expiryDate'],mismatch=fields.filter(field=>String(readBack?.[field]??'')!==String(updated?.[field]??''));
      diag.record('persistence comparison',{itemId:editId,requestedUpdate:update,persistedRecord:diag.itemSnapshot(readBack),result:mismatch.length?'mismatch':'match',mismatchedFields:mismatch});
      if(pendingImageFile&&oldImageRef&&oldImageRef!==newImageRef&&!usedByOther(oldImageRef,editId))try{await media.remove(oldImageRef);}catch(_){}
      diag.record('in-memory state update start',{itemId:editId});diag.record('in-memory state update end',{itemId:editId,renderSource:diag.itemSnapshot(inv().items.find(x=>String(x.id)===String(editId)))});
      diag.record('detail rerender start',{itemId:editId});if(editorReturnToDetail)renderItemDetail(editId);diag.record('detail rerender end',{itemId:editId});
      closeItemEditor();diag.record('list rerender start',{itemId:editId});render();diag.record('list rerender end',{itemId:editId});diag.record('completion',{itemId:editId,result:mismatch.length?'persisted mismatch':'success'});
    }
    async function deleteItem(id){const item=inv().items.find(x=>x.id===id);if(!item||!confirm('确定永久删除这个物品吗？历史订单不会删除，库存数量也不会回滚。'))return;inv().items=inv().items.filter(x=>x.id!==id);const orders=getState().orders?.items||[];orders.forEach(order=>(order.items||[]).forEach(line=>{if(line.inventoryItemId===id)line.inventoryItemId='';const events=Array.isArray(line.inventoryImports)?line.inventoryImports:(line.inventoryImport?[line.inventoryImport]:[]);events.forEach(event=>{if(event.inventoryItemId===id)event.linkedItemDeleted=true;});if(line.inventoryImport?.inventoryItemId===id)line.inventoryImport.linkedItemDeleted=true;}));save();if(item.imageRef&&!usedByOther(item.imageRef,id))try{await media.remove(item.imageRef);}catch(_){}render();}
    function archiveItem(id){const item=inv().items.find(x=>x.id===id);if(!item)return;item.status='archived';item.updatedAt=Date.now();save();render();}
    function restoreItem(id){const item=inv().items.find(x=>x.id===id);if(!item)return;item.status='active';item.updatedAt=Date.now();save();render();}
    function openSettings(){renderSettings();modal.open('inventorySettingsModal');}
    function closeSettings(){modal.close('inventorySettingsModal');}
    function renderSettings(){const state=inv();qs('#inventoryCategoriesList').innerHTML=state.categories.length?state.categories.map((x,i)=>`<div class="manage-row"><span>${esc(x)}</span><button onclick="renameInventoryCategory(${i})">编辑</button><button class="danger" onclick="deleteInventoryCategory(${i})">删除</button></div>`).join(''):'<span class="small">暂无自定义分类。</span>';qs('#inventoryLocationsList').innerHTML=state.locations.length?state.locations.map((x,i)=>`<div class="manage-row"><span>${esc(x)}</span><button onclick="renameInventoryLocation(${i})">编辑</button><button class="danger" onclick="deleteInventoryLocation(${i})">删除</button></div>`).join(''):'<span class="small">暂无自定义位置。</span>';}
    function addManaged(kind){const input=qs(kind==='category'?'#newInventoryCategory':'#newInventoryLocation'),value=input.value.trim();if(!value)return;const list=kind==='category'?inv().categories:inv().locations;if(!list.includes(value))list.push(value);input.value='';save();renderSettings();}
    function renameManaged(kind,index){const list=kind==='category'?inv().categories:inv().locations,old=list[index],next=prompt('请输入新名称',old)?.trim();if(!next||next===old)return;inv().items.forEach(i=>{if(i[kind]===old)i[kind]=next;});list[index]=next;save();renderSettings();render();}
    function deleteManaged(kind,index){const list=kind==='category'?inv().categories:inv().locations,value=list[index],used=inv().items.some(i=>i[kind]===value);if(used){alert('该名称正在被库存物品使用，请先修改这些物品。');return;}if(!confirm(`确定删除 ${value} 吗？`))return;list.splice(index,1);save();renderSettings();}
    function render(){const state=inv(),search=(qs('#inventorySearch')?.value||'').trim().toLowerCase(),category=qs('#inventoryCategoryFilter')?.value||'',location=qs('#inventoryLocationFilter')?.value||'',sort=currentSort();fillFilter('inventoryCategoryFilter',allCategories(),category,'所有分类');fillFilter('inventoryLocationFilter',allLocations(),location,'所有位置');let list=state.items.filter(i=>activeFilter==='archived'?i.status==='archived':i.status!=='archived');if(activeFilter==='low')list=list.filter(i=>itemStatus(i)==='low');if(activeFilter==='expiring')list=list.filter(i=>itemStatus(i)==='expiring');if(activeFilter==='expired')list=list.filter(i=>itemStatus(i)==='expired');if(search)list=list.filter(i=>[i.name,i.category,i.location,(i.tags||[]).join(' '),i.notes].join(' ').toLowerCase().includes(search));if(category)list=list.filter(i=>i.category===category);if(location)list=list.filter(i=>i.location===location);list.sort(sortItems(sort,state.items));const active=state.items.filter(i=>i.status!=='archived'),summary={total:active.length,low:active.filter(i=>itemStatus(i)==='low').length,expiring:active.filter(i=>['expiring','expired'].includes(itemStatus(i))).length};qs('#inventoryMetrics').innerHTML=`<div class="metric"><b>${summary.total}</b><span>Items</span></div><div class="metric"><b>${summary.low}</b><span>Low Stock</span></div><div class="metric"><b>${summary.expiring}</b><span>Expiring</span></div>`;renderUseOneSnackbar();qs('#inventoryList').innerHTML=list.length?list.map(card).join(''):'<div class="entry"><span class="small">还没有库存物品。新建第一条记录吧。</span></div>';}
    function fillFilter(id,values,current,label){const el=qs('#'+id);if(!el)return;el.innerHTML=`<option value="">${label}</option>`+values.map(v=>`<option value="${esc(v)}">${esc(v)}</option>`).join('');el.value=current;}
    function sortItems(sort,canonicalItems=[]){return sortLogic.sortItems(sort,canonicalItems);}
    function card(i){const status=itemStatus(i),badges=[status==='low'?'Low Stock':'',status==='expiring'?'Expiring Soon':'',status==='expired'?'Expired':''].filter(Boolean),quantity=Math.max(0,Number(i.quantity)||0),disabled=quantity<=0?' disabled':'';return `<article class="tool-card inventory-card" onclick="inventoryTraceOpenDetail('${i.id}',event)"><div class="inventory-thumb ${i.imageRef?'has-image':''}" data-inventory-image="${esc(i.imageRef||'')}">⌂</div><div class="inventory-copy"><h3>${esc(i.name)}</h3><div class="meta">${esc(fmt(i))} · ${esc(i.category)} · ${esc(i.location)}</div>${badges.map(x=>`<span class="status-pill inventory-${x.replace(' ','-').toLowerCase()}">${x}</span>`).join('')}</div><div class="tool-actions" onclick="event.stopPropagation()"><button type="button" class="inventory-use-one" aria-label="${esc(i18n.t('useOneAria'))}" title="${esc(i18n.t('useOne'))}"${disabled} onclick="inventoryUseOne('${i.id}',event)"><span aria-hidden="true">−1</span><span class="sr-only">${esc(i18n.t('useOne'))}</span></button><button onclick="inventoryTraceOpenDetail('${i.id}',event)">编辑</button>${i.status==='archived'?`<button onclick="restoreInventoryItem('${i.id}')">恢复</button>`:`<button onclick="archiveInventoryItem('${i.id}')">归档</button>`}<button class="danger" onclick="deleteInventoryItem('${i.id}')">删除</button></div></article>`;}
    async function hydrateImages(){for(const el of document.querySelectorAll('[data-inventory-image]')){const id=el.dataset.inventoryImage;if(!id)continue;try{const rec=await media.get(id);if(rec?.blob){const url=URL.createObjectURL(rec.blob);el.innerHTML=`<img src="${url}" alt="">`;setTimeout(()=>URL.revokeObjectURL(url),60000);}}catch(_){}}}
    function setFilter(value,button){activeFilter=value;document.querySelectorAll('#inventoryFilters button').forEach(b=>b.classList.remove('on'));button?.classList.add('on');render();hydrateImages();}
    function sourceOrderSummary(item){const orders=getState().orders?.items||[],sources=(item.sourceOrders||[]).slice().reverse();return sources.length?`<section class="inventory-source-section"><div class="section-head"><h3>订单入库记录</h3></div><div class="inventory-source-list">${sources.map(s=>{const order=orders.find(o=>String(o.id)===String(s.orderId)),reversed=s.status==='reversed';return `<article class="inventory-source-row"><div><b>${esc(reversed?'订单入库 +'+(s.quantity||0)+' · 已撤销':'订单入库 +'+(s.quantity||0))}</b><small>${esc(String(s.importedAt||'').slice(0,10))}${order?.sellerNameSnapshot?` · ${esc(order.sellerNameSnapshot)}`:''}${s.sourceOrderDeleted||(!order&&s.orderId)?' · 原订单已删除':''}</small></div>${order&&!s.sourceOrderDeleted?`<button type="button" class="ghost inventory-source-link" onclick="openInventorySourceOrder('${esc(order.id)}')">查看订单 ›</button>`:''}</article>`;}).join('')}</div></section>`:'<p class="section-note">尚无订单入库记录。</p>';}
    function renderItemDetail(id){diag.record('detail rerender start',{itemId:id,detailItemId:detailId});const item=inv().items.find(x=>String(x.id)===String(id));if(!item){diag.record('completion/error',{itemId:id,error:'detail record missing'});modal.close('inventoryDetailModal');return;}detailId=id;qs('#inventoryDetailTitle').textContent=item.name||'库存物品';qs('#inventoryDetailContent').innerHTML=`<section class="inventory-detail-summary" aria-label="库存概要"><div><span>当前库存</span><b>${esc(fmt(item))}</b></div><div><span>分类</span><b>${esc(item.category||'Other')}</b></div><div><span>位置</span><b>${esc(item.location||'Other')}</b></div></section><section class="inventory-detail-meta" aria-label="库存信息"><div><span>购买日期</span><b>${esc(item.purchaseDate||'—')}</b></div><div><span>到期日期</span><b>${esc(item.expiryDate||'—')}</b></div><div><span>最低库存</span><b>${esc(`${item.minQuantity??0} ${item.unit||'pcs'}`)}</b></div><div><span>Tags</span><b>${esc((item.tags||[]).join(', ')||'—')}</b></div><div class="full"><span>Notes</span><b>${esc(item.notes||'—')}</b></div></section>${sourceOrderSummary(item)}`;diag.record('detail rerender end',{itemId:id,renderedRecord:diag.itemSnapshot(item)});}
    function openInventoryItem(id){qs('#inventoryDetailModal').dataset.itemId=String(id||'');diag.record('inventory detail opened',{itemId:id});renderItemDetail(id);modal.open('inventoryDetailModal');}
    function closeInventoryDetail(){diag.record('modal close',{itemId:detailId,modal:'inventoryDetailModal'});detailId='';modal.close('inventoryDetailModal');}
    function editInventoryFromDetail(){diag.record('edit button clicked',{itemId:detailId,detailItemId:detailId});if(!detailId){diag.record('completion/error',{error:'missing detail item id'});return;}modal.push('inventoryDetailModal','inventoryModal',{flow:'inventory-detail-edit'});openItemEditor(detailId,{returnToDetail:true});}
    function openSourceOrder(orderId){const order=getState().orders?.items?.find(x=>String(x.id)===String(orderId));if(!order){alert('原订单已删除');return;}modal.push('inventoryDetailModal','orderModal',{flow:'inventory-source-order'});window.openOrderEditor?.(order.id);}
    function findSimilar(name){const a=tokens(name);return inv().items.filter(i=>i.status!=='archived').filter(i=>{const b=tokens(i.name),overlap=[...a].filter(x=>x.length>2&&b.has(x)).length;return normalized(i.name)===normalized(name)||overlap>0;}).slice(0,3);}
    function restockItem(id,quantity,sourceOrderId){const item=inv().items.find(i=>i.id===id);if(!item)return null;const importedAt=new Date().toISOString(),delta=Number(quantity)||0;item.quantity=Math.max(0,(Number(item.quantity)||0)+delta);item.lastRestockedAt=importedAt;item.sourceOrderId=sourceOrderId||item.sourceOrderId||'';item.sourceOrders.push({orderId:sourceOrderId||'',orderItemId:'',quantity:delta,importedAt});item.history.push({id:`inventory-history-${Date.now()}`,date:importedAt,kind:'order_import',message:`订单入库 +${delta}`,orderId:sourceOrderId||'',quantityDelta:delta});item.updatedAt=Date.now();save();return item;}
    function createFromOrder(data){const importedAt=new Date().toISOString(),quantity=Math.max(0,Number(data.quantity)||0),item={id:`inventory-${Date.now()}-${Math.random().toString(36).slice(2,7)}`,name:data.name||'Order item',category:data.category||'Other / 其他',quantity,unit:data.unit||'pcs',location:data.location||'Other',imageRef:'',purchaseDate:data.purchaseDate||'',expiryDate:'',minQuantity:0,lowStockEnabled:false,notes:data.notes||'',tags:[],status:'active',sourceOrderId:data.sourceOrderId||'',sourceOrders:data.sourceOrderId?[{orderId:data.sourceOrderId,orderItemId:data.orderItemId||'',quantity,importedAt}]:[],history:data.sourceOrderId?[{id:`inventory-history-${Date.now()}`,date:importedAt,kind:'order_import',message:`订单入库 +${quantity}`,orderId:data.sourceOrderId,orderItemId:data.orderItemId||'',quantityDelta:quantity}]:[],lastRestockedAt:importedAt,createdAt:Date.now(),updatedAt:Date.now()};inv().items.push(item);save();return item;}
    return {render:()=>{render();hydrateImages();},openItemEditor,closeItemEditor,saveItem,deleteItem,archiveItem,restoreItem,openInventoryItem,closeInventoryDetail,editInventoryFromDetail,openSourceOrder,imageChanged,updateSimilar,toggleCustom,openSettings,closeSettings,addManaged,renameManaged,deleteManaged,setFilter,setSort,findSimilar,restockItem,createFromOrder,useOne,undoUseOne};
  }
  window.JournalModules=window.JournalModules||{};window.JournalModules.createInventoryModule=createInventoryModule;window.JournalModules.createInventoryUseOneLogic=createInventoryUseOneLogic;window.JournalModules.createInventorySortLogic=createInventorySortLogic;
})();
