(function(){
  'use strict';
  const DB_NAME='personal-life-hub', DB_VERSION=3, MEDIA_STORE='media', SNAPSHOT_STORE='snapshots', LEGACY_JOURNAL_PAYLOAD_STORE='legacyJournalPayloads';
  let dbPromise;
  function open(){if(dbPromise)return dbPromise;dbPromise=new Promise((resolve,reject)=>{const request=indexedDB.open(DB_NAME,DB_VERSION);request.onupgradeneeded=()=>{const db=request.result;if(!db.objectStoreNames.contains(MEDIA_STORE))db.createObjectStore(MEDIA_STORE,{keyPath:'id'});if(!db.objectStoreNames.contains(SNAPSHOT_STORE))db.createObjectStore(SNAPSHOT_STORE,{keyPath:'snapshotId'});if(!db.objectStoreNames.contains(LEGACY_JOURNAL_PAYLOAD_STORE))db.createObjectStore(LEGACY_JOURNAL_PAYLOAD_STORE,{keyPath:'id'});};request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error);});return dbPromise;}
  async function run(storeName,mode,fn){const db=await open();return new Promise((resolve,reject)=>{const tx=db.transaction(storeName,mode),store=tx.objectStore(storeName);let result;try{result=fn(store)}catch(error){reject(error);return}tx.oncomplete=()=>resolve(result?.result);tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error);});}
  const uid=()=>`media-${Date.now()}-${Math.random().toString(36).slice(2,9)}`;
  function createMediaStore(options={}){const mediaDbName=String(options.dbName||DB_NAME),mediaDbVersion=Number(options.dbVersion)||DB_VERSION,mediaStoreName=String(options.mediaStoreName||MEDIA_STORE),snapshotStoreName=String(options.snapshotStoreName||SNAPSHOT_STORE);let mediaDbPromise;function openMedia(){if(mediaDbPromise)return mediaDbPromise;mediaDbPromise=new Promise((resolve,reject)=>{const request=indexedDB.open(mediaDbName,mediaDbVersion);request.onupgradeneeded=()=>{const db=request.result;if(!db.objectStoreNames.contains(mediaStoreName))db.createObjectStore(mediaStoreName,{keyPath:'id'});if(!db.objectStoreNames.contains(snapshotStoreName))db.createObjectStore(snapshotStoreName,{keyPath:'snapshotId'});if(!db.objectStoreNames.contains(LEGACY_JOURNAL_PAYLOAD_STORE))db.createObjectStore(LEGACY_JOURNAL_PAYLOAD_STORE,{keyPath:'id'});};request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error);});return mediaDbPromise;}async function runMedia(mode,fn){const db=await openMedia();return new Promise((resolve,reject)=>{const tx=db.transaction(mediaStoreName,mode),store=tx.objectStore(mediaStoreName);let result;try{result=fn(store)}catch(error){reject(error);return}tx.oncomplete=()=>resolve(result?.result);tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error);});}async function putBlob(blob,meta={}){if(!(blob instanceof Blob))throw new Error('Invalid media blob');const record={id:meta.id||uid(),blob,mime:blob.type||meta.mime||'application/octet-stream',createdAt:meta.createdAt||Date.now(),ownerType:meta.ownerType||'',ownerId:meta.ownerId||''};await runMedia('readwrite',store=>store.put(record));return {id:record.id,mime:record.mime,createdAt:record.createdAt,ownerType:record.ownerType,ownerId:record.ownerId};}function get(id){return id?runMedia('readonly',store=>store.get(id)):Promise.resolve(undefined);}async function remove(id){if(id)await runMedia('readwrite',store=>store.delete(id));}function list(){return runMedia('readonly',store=>store.getAll());}
  async function toBase64(blob){const buffer=await blob.arrayBuffer();let binary='';const bytes=new Uint8Array(buffer);for(let i=0;i<bytes.length;i+=0x8000)binary+=String.fromCharCode(...bytes.subarray(i,i+0x8000));return btoa(binary);}
  function fromBase64(data,mime){const binary=atob(data),bytes=new Uint8Array(binary.length);for(let i=0;i<binary.length;i++)bytes[i]=binary.charCodeAt(i);return new Blob([bytes],{type:mime||'application/octet-stream'});}
  async function exportForBackup(){const records=await list();return Promise.all((records||[]).map(async record=>({id:record.id,mime:record.mime,createdAt:record.createdAt,ownerType:record.ownerType,ownerId:record.ownerId,data:await toBase64(record.blob)})));}
  async function restoreFromBackup(records){if(!Array.isArray(records))return;for(const record of records){if(!record?.id||typeof record.data!=='string')throw new Error('Invalid media backup');await runMedia('readwrite',store=>store.put({...record,blob:fromBase64(record.data,record.mime),createdAt:record.createdAt||Date.now(),ownerType:record.ownerType||'',ownerId:record.ownerId||''}));}}
  async function getAttachmentMedia(reference){if(!reference||typeof reference.mediaId!=='string'||!reference.mediaId)return undefined;return get(reference.mediaId);}
  async function getAttachmentBundle(reference){const primary=await getAttachmentMedia(reference),companion=reference?.companionMediaId?await get(reference.companionMediaId):undefined;return {primary,companion};}
  return {putBlob,get,remove,list,exportForBackup,restoreFromBackup,getAttachmentMedia,getAttachmentBundle,contract:{dbName:mediaDbName,dbVersion:mediaDbVersion,mediaStoreName,keyPath:'id'}};}
  function createLegacyJournalPayloadStore(options={}){const dbName=String(options.dbName||DB_NAME),dbVersion=Number(options.dbVersion)||DB_VERSION,storeName=String(options.storeName||LEGACY_JOURNAL_PAYLOAD_STORE);let payloadDbPromise;function openPayload(){if(payloadDbPromise)return payloadDbPromise;payloadDbPromise=new Promise((resolve,reject)=>{const request=indexedDB.open(dbName,dbVersion);request.onupgradeneeded=()=>{const db=request.result;if(!db.objectStoreNames.contains(MEDIA_STORE))db.createObjectStore(MEDIA_STORE,{keyPath:'id'});if(!db.objectStoreNames.contains(SNAPSHOT_STORE))db.createObjectStore(SNAPSHOT_STORE,{keyPath:'snapshotId'});if(!db.objectStoreNames.contains(storeName))db.createObjectStore(storeName,{keyPath:'id'});};request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error);});return payloadDbPromise;}async function runPayload(mode,fn){const db=await openPayload();return new Promise((resolve,reject)=>{const tx=db.transaction(storeName,mode),objectStore=tx.objectStore(storeName);let result;try{result=fn(objectStore)}catch(error){reject(error);return}tx.oncomplete=()=>resolve(result?.result);tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error);});}return {put:record=>runPayload('readwrite',store=>store.put(record)),get:id=>id?runPayload('readonly',store=>store.get(id)):Promise.resolve(undefined),remove:id=>id?runPayload('readwrite',store=>store.delete(id)):Promise.resolve(),list:()=>runPayload('readonly',store=>store.getAll()),contract:{dbName,dbVersion,storeName,keyPath:'id'}};}
  const snapshotBytes=payload=>new Blob([JSON.stringify(payload)]).size;
  function validSnapshot(record,expectedId=''){return !!record&&(!expectedId||record.snapshotId===expectedId)&&record.payload&&typeof record.payload==='object'&&Number(record.schemaVersion)>=0&&Number(record.payloadBytes)===snapshotBytes(record.payload);}
  const snapshotStore={async put(record){if(!record?.snapshotId||!record.payload||typeof record.payload!=='object')throw new Error('Invalid snapshot payload');const prepared={snapshotId:record.snapshotId,createdAt:record.createdAt||new Date().toISOString(),reason:record.reason||'',appVersion:record.appVersion||'',schemaVersion:Number(record.schemaVersion)||0,dataVersion:Number(record.dataVersion)||1,recordCounts:record.recordCounts&&typeof record.recordCounts==='object'?record.recordCounts:{},checksum:record.checksum||'',payload:record.payload,payloadBytes:snapshotBytes(record.payload)};await run(SNAPSHOT_STORE,'readwrite',store=>store.put(prepared));const readBack=await run(SNAPSHOT_STORE,'readonly',store=>store.get(prepared.snapshotId));if(!validSnapshot(readBack,prepared.snapshotId))throw new Error('Snapshot read-back validation failed');return readBack;},get:id=>run(SNAPSHOT_STORE,'readonly',store=>store.get(id)),async remove(id){if(id)await run(SNAPSHOT_STORE,'readwrite',store=>store.delete(id));},async list(){return (await run(SNAPSHOT_STORE,'readonly',store=>store.getAll())||[]).map(record=>({...record,payload:undefined}));},validate:validSnapshot};
  window.JournalModules=window.JournalModules||{};
  window.JournalModules.createMediaStore=createMediaStore;
  window.JournalModules.createSnapshotStore=()=>snapshotStore;
  window.JournalModules.createLegacyJournalPayloadStore=createLegacyJournalPayloadStore;
})();
