(function(){
  'use strict';
  function createSellersModule(ctx){
    const {qs,esc,getState,save,modal}=ctx;
    let editId='',locationEditId='',afterSave=null,navigation=null,locationNavigation=null;
    const uid=prefix=>`${prefix}-${Date.now()}-${Math.random().toString(36).slice(2,7)}`;
    function data(){const s=getState();s.orders=s.orders&&typeof s.orders==='object'?s.orders:{items:[],sellers:[],pickupLocations:[],recurring:[],forwardingBatches:[]};['items','sellers','pickupLocations','recurring','forwardingBatches'].forEach(k=>s.orders[k]=Array.isArray(s.orders[k])?s.orders[k]:[]);return s.orders;}
    function populateLocations(selected=''){const el=qs('#sellerPickupLocation');if(!el)return;const rows=data().pickupLocations;el.innerHTML='<option value="">不指定</option>'+rows.map(x=>`<option value="${esc(x.id)}">${esc(x.name)}</option>`).join('');el.value=selected||'';}
    function openSellerEditor(id='',callback=null,nav=null){editId=id;afterSave=callback;navigation=nav;const item=id?data().sellers.find(x=>x.id===id):null;qs('#sellerModalTitle').textContent=item?'编辑卖家':'新增卖家';qs('#sellerName').value=item?.name||'';qs('#sellerFulfillment').value=item?.defaultFulfillmentType||'direct';populateLocations(item?.defaultPickupLocationId||'');qs('#sellerAddress').value=item?.defaultAddress||'';qs('#sellerWebsite').value=item?.website||'';qs('#sellerNotes').value=item?.notes||'';if(modal.isOpen('sellerListModal'))modal.push('sellerListModal','sellerModal',{flow:'seller-manager-editor'});else modal.open('sellerModal');}
    function closeSellerEditor(){const nav=navigation;afterSave=null;navigation=null;modal.pop('sellerModal');if(nav?.onCancel)nav.onCancel();}
    function saveSeller(){const name=qs('#sellerName').value.trim();if(!name){alert('请填写卖家名称');return;}const d={name,defaultFulfillmentType:qs('#sellerFulfillment').value,defaultPickupLocationId:qs('#sellerPickupLocation').value,defaultAddress:qs('#sellerAddress').value.trim(),website:qs('#sellerWebsite').value.trim(),notes:qs('#sellerNotes').value.trim(),updatedAt:Date.now()};let item;if(editId){item=data().sellers.find(x=>x.id===editId);if(item)Object.assign(item,d);}else{item={id:uid('seller'),createdAt:Date.now(),...d};data().sellers.push(item);}const result=save();if(!result?.ok)return result;const callback=afterSave,nav=navigation;afterSave=null;navigation=null;render();modal.pop('sellerModal');if(callback)callback(item);if(nav?.onSave)nav.onSave(item);return result;}
    function deleteSeller(id){const orders=data().items.filter(x=>x.sellerId===id).length;if(orders&&!confirm(`这个卖家仍被 ${orders} 条历史订单引用。删除不会影响订单快照，确定继续吗？`))return;if(!orders&&!confirm('确定删除这个卖家吗？'))return;data().sellers=data().sellers.filter(x=>x.id!==id);save();render();}
    function openSellerList(){render();modal.open('sellerListModal');}
    function closeSellerList(){modal.close('sellerListModal');}
    function openPickupLocationEditor(id='',nav=null){locationEditId=id;locationNavigation=nav;const x=id?data().pickupLocations.find(v=>v.id===id):null;qs('#pickupLocationTitle').textContent=x?'编辑取货点':'新增取货点';qs('#pickupLocationName').value=x?.name||'';qs('#pickupLocationAddress').value=x?.address||'';qs('#pickupLocationNotes').value=x?.notes||'';renderPickupLocations();if(modal.isOpen('sellerListModal'))modal.push('sellerListModal','pickupLocationModal',{flow:'seller-manager-pickup-manager'});else modal.open('pickupLocationModal');}
    function closePickupLocationEditor(){const nav=locationNavigation;locationNavigation=null;modal.pop('pickupLocationModal');if(nav?.onCancel)nav.onCancel();}
    function savePickupLocation(){const name=qs('#pickupLocationName').value.trim(),address=qs('#pickupLocationAddress').value.trim();if(!name||!address){alert('请填写取货点名称和地址');return;}const d={name,address,notes:qs('#pickupLocationNotes').value.trim(),updatedAt:Date.now()};let item;if(locationEditId){item=data().pickupLocations.find(v=>v.id===locationEditId);if(item)Object.assign(item,d);}else{item={id:uid('pickup'),createdAt:Date.now(),...d};data().pickupLocations.push(item);}const result=save();if(!result?.ok)return result;const nav=locationNavigation;locationNavigation=null;qs('#pickupLocationName').value='';qs('#pickupLocationAddress').value='';qs('#pickupLocationNotes').value='';locationEditId='';renderPickupLocations();render();modal.pop('pickupLocationModal');if(nav?.onSave)nav.onSave(item);return result;}
    function deletePickupLocation(id){if(!confirm('确定删除这个取货点吗？历史订单的地址快照不会改变。'))return;data().pickupLocations=data().pickupLocations.filter(x=>x.id!==id);data().sellers.forEach(x=>{if(x.defaultPickupLocationId===id)x.defaultPickupLocationId='';});save();renderPickupLocations();render();}
    function renderPickupLocations(){const el=qs('#pickupLocationsList');if(!el)return;el.innerHTML=data().pickupLocations.length?data().pickupLocations.map(x=>`<div class="manage-row"><span><b>${esc(x.name)}</b><small>${esc(x.address)}</small></span><span><button onclick="openPickupLocationEditor('${x.id}')">编辑</button><button class="danger" onclick="deletePickupLocation('${x.id}')">删除</button></span></div>`).join(''):'<span class="small">还没有取货点。</span>';}
    function render(){const el=qs('#sellerList');if(el){const rows=data().sellers.slice().sort((a,b)=>a.name.localeCompare(b.name));el.innerHTML=(rows.length?rows.map(x=>`<div class="manage-row"><span><b>${esc(x.name)}</b><small>${esc(x.defaultAddress||x.defaultFulfillmentType||'')}</small></span><span><button onclick="openSellerEditor('${x.id}')">编辑</button><button class="danger" onclick="deleteSeller('${x.id}')">删除</button></span></div>`).join(''):'<div class="entry"><span class="small">还没有卖家。可在新订单里直接新增。</span></div>')+`<button class="ghost" onclick="openPickupLocationEditor()">管理取货点</button>`;}}
    return {data,render,openSellerEditor,closeSellerEditor,saveSeller,deleteSeller,openSellerList,closeSellerList,populateLocations,openPickupLocationEditor,closePickupLocationEditor,savePickupLocation,deletePickupLocation,renderPickupLocations};
  }
  window.JournalModules=window.JournalModules||{};window.JournalModules.createSellersModule=createSellersModule;
})();
